name: Build and Push to GHCR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        default: '0.1.0'

permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase repository owner
      id: repo_owner
      run: echo "repo_owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ../../SolutionAnalyzer.Mcp/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ steps.repo_owner.outputs.repo_owner_lc }}/solution-analyzer:latest
          ghcr.io/${{ steps.repo_owner.outputs.repo_owner_lc }}/solution-analyzer:${{ github.event.inputs.image_tag }}
